revtel/react-native-nfc-manager

NfcManager.js, README.md, android/src/main/java/community/revteltech/nfc/NfcManager.java, ios/NfcManager.m
This pull request adds 2 features. 
The first is the ability to add a custom message such as "Hold iPhone near the fire" shown below.
The second is the ability to have the popup automatically close when a tag is scanned & not have to click the "done" button to close the popup.
=> (Ios) add custom message & allow message to automatically close on scan

README.md
I don't feel like people should have to modify a module to change the behaviour off it however i don't have any solution for it right now so this is important information to have.
This adds relevant info about hardware permissions for android mentioned in issue #16
=> Added description for NFC hardware support on Android

ios/NfcManager.h, ios/NfcManager.xcodeproj/project.pbxproj, ios/NfcManager.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ios/NfcManager.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Thanks for your job with this library.
I have some errors with [import quote style](https://github.com/whitedogg13/react-native-nfc-manager/compare/master...ieschalier:master#diff-acd4310b9c89341462cfcd4a502d4c88L4) in IOS Project : 
So i make quick update to fix that.
I also add [header search path](https://github.com/whitedogg13/react-native-nfc-manager/compare/master...ieschalier:master#diff-0f42f84cd09e18166a2fa8bd74d449c2R155). So now react-native-nfc-manager work out of the box with expokit projects.
=> Quote style and add header search path

index.d.ts
Hi there
I added a missing definition for the parseText function.
Thanks for creating react-native-nfc-manager!
=> added missing definition for parseText

README.md
Moving version history to the end of the readme. Readme is now easier on the eyes I believe.
=> move version history to end of readme

NfcManager.js, android/src/main/java/community/revteltech/nfc/NfcManager.java, android/src/main/java/community/revteltech/nfc/TagTechnologyRequest.java
Added basic support for MifareClassic cards. Any feedback / suggestions welcome to get this PR merged upstream.
Usage sample:
```
NfcManager.requestTechnology(NfcTech.MifareClassic)
.then(() => {
NfcManager.mifareClassicAuthenticateA(2, String.fromCharCode(0xff, 0xff, 0xff, 0xff, 0xff, 0xff)).then(() => {
NfcManager.getMifareClassicMessage(2)
.then(data => {
console.log('Received MifareClassic data', data);
return;
})
.catch(err => {
console.log('Failed to read data: ', err);
});
})
.catch(err => {
console.log('Failed to authenticate: ', err);
});
})
.catch(err => {
console.log('Failed to tech request: ', err);
});
```
=> added basic mifareclassic support

android/src/main/java/community/revteltech/nfc/TagTechnologyRequest.java
From Firebase:
--------------
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean android.nfc.Tag.hasTech(int)' on a null object reference
android.nfc.tech.MifareClassic.get (MifareClassic.java:136)
community.revteltech.nfc.TagTechnologyRequest.connect (TagTechnologyRequest.java:52) <---
community.revteltech.nfc.NfcManager.parseNfcIntent (NfcManager.java:687)
community.revteltech.nfc.NfcManager.onNewIntent (NfcManager.java:657)
com.facebook.react.bridge.ReactContext.onNewIntent (ReactContext.java:197)
com.facebook.react.ReactInstanceManager.onNewIntent (ReactInstanceManager.java:455)
com.facebook.react.ReactActivityDelegate.onNewIntent (ReactActivityDelegate.java:179)
com.facebook.react.ReactActivity.onNewIntent (ReactActivity.java:107) …
=> Fix a bugfix that sometimes occurs when the tag is a null object

ios/NfcManager.m
Closes #112 
Handles sporadic
```
Crashed: com.facebook.react.NfcManagerQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x50435f4462f88092
```
in iOS
=> Catch exception during NFCNDEFReaderSession.readingAvailable

NfcManager.js, README.md, android/src/main/java/community/revteltech/nfc/NfcManager.java, index.d.ts, ios/NfcManager.m
`enableForegroundDispatch` listens for all types of tag events and doesn't work well for my use-cases. With this you can now fine-tune the types of tags and NFC actions the reader listens to.
---
I don't know Objective-C and didn't test the changes there. It would be great if someone could compile/test this.
=> Added support for `NfcAdapter.enableReaderMode`

NfcManager.js
An invocation of `NfcManager.stop()` shouldn't throw an error when `NfcManager.start()` hasn't been called or has failed.
=> Fixed NfcManager.stop()

ndef-lib/index.js
When there is a record with `header.il === false`, in the variable `id_length` will remain a value from the previous record (previous while cycle). In some situations it could result in malformed records that follows an record with `header.il === false`.
=> Fixed id_length in decodeMessage.

android/src/main/java/community/revteltech/nfc/JsonConvert.java
All other types than boolean is being returned to react, so I just added a type check for primitive booleans.
=> Make boolean values accessible in react, e.g. "isWriteable" and "canMakeReadonly"

android/src/main/java/community/revteltech/nfc/JsonConvert.java
Hi. 
Sorry, my last patch contained the wrong variable name in jsonToReact().
This will fix it.
v2.1.7 wont compile, because I'm trying to access a variable named `writableMap`, but should instead use `writableArray`.
Best regards,
Christian.
=> Fix jsonToReact(JSONArray jsonArray) when parsing boolean

index.d.ts
A small update to requestTechnology, previous declaration only accepted a single NfcTech and no options param.
The update makes tech argument accept single value or array of NfcTech and adds options parameter as optional RegisterTagEventOpts (I believe that's the correct type).
Thanks for creating, sharing and maintaining this library!
=> Type definition NfcManager.requestTechnology

NfcManager.js, index.d.ts, ios/NfcManager.m
Adds and ability to read multiple blocks at once for iso15693.
Blocks returned are not joined returning an array of array which should be fine for most cases.
Range is specified using two separate variables as common in javascript.
=> Add readMultipleBlocks method for iso15693 on iOS

APIv1.md, NfcManager.js, android/src/main/java/community/revteltech/nfc/NfcManager.java, index.d.ts
Hello!
I was noticed that after detection one tag should pass about 10 seconds to detect another (because of NfcAdapter.EXTRA_READER_PRESENCE_CHECK_DELAY). It could be not very convenient when you read one-to-one tags. I decided to add new parameter `readerModeDelay` which set delay between tag detection. Default value of parameter is 10 seconds (to save backward compatibility).
=> add readerModeDelay param

ios/NfcManager.m
Some NFC Tags (e.g. ST25DV) require the block adress to be 16 bits long in order to use extended commands (e.g. extendedReadSingleBlock) if the value exceeds 256, because of multiple NDEF areas management, so a simple type change does the trick.
=> Set blockNumber param as uint16_t

README.md, app.plugin.js, package-lock.json, package.json
With Expo SDK 41 we've rolled out an interface called [config plugins](https://docs.expo.io/guides/config-plugins/) which lets users add native modules that aren't in the Expo Go app to their native cloud builds and locally when [prebuilding](https://expo.fyi/prebuilding).
This is a [highly requested package](https://expo.canny.io/feature-requests/p/nfc) so I've created the plugin personally.
We’re still working on improving the development experience for config plugins and custom managed workflow, feel free to add any feedback. People won’t be able to use this in an Expo-Go-like-app until we release “Expo Development Client” ([more info](https://blog.expo.io/expo-managed-workflow-in-2021-d1c9b68aa10)). 
- Added a `app.plugin.js` as the main entry point to the plugin. Plugins must run in …
=> Created Expo config plugin

README.md, app.plugin.js
Follow up to https://github.com/whitedogg13/react-native-nfc-manager/pull/399#issuecomment-849588150
Added support for a `selectIdentifiers` prop in the config plugin. This will populate the `com.apple.developer.nfc.readersession.iso7816.select-identifiers` entitlement on iOS.
=> [config plugin] Added support for selectIdentifiers

README.md, app.plugin.js, package.json
[Follow up](https://github.com/revtel/react-native-nfc-manager/pull/400#issuecomment-891327197). Fixed select-identifiers being added in the wrong place. Also added support for [system codes](https://developer.apple.com/documentation/bundleresources/information_property_list/systemcodes).
Added to a project and used prebuild previews to see if code was being added to the correct location (Info.plist instead of entitlements).
=> [Expo Config Plugin] Fixed select identifiers and added system codes support

android/src/main/java/community/revteltech/nfc/NfcManager.java
Hi!
We spotted this issue on our project and I managed to track down the right flags for it to work in Android below 12 and above 12.
I used this project to find the flags, so not sure if anything else could be added: https://github.com/metrodroid/metrodroid/blob/00453e7fc3c39dbdb570ad1ff2d5d76d83519393/src/main/java/au/id/micolous/metrodroid/activity/MainActivity.kt#L74
This is the error:
Error text for search engine visibility:
```
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```
=> fix(android): explicitly set intent FLAG_MUTABLE for android 12+ support

setup.md
Users not familiar with IOS NFC will not know to add a 
<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>.   I believe this should be added in the setup.md file.
=> ISO setup.md could be more enlightening. 

README.md, app.plugin.js, package.json
- fix https://github.com/revtel/react-native-nfc-manager/issues/473
- Bump `@expo/config-plugins`
- Ensure `compileSdkVersion` is at least 31
- `npm pack`
- `yarn add /path/to/module.tgz`
- `expo prebuild -p android --no-install` -> `android/build.gradle` `compileSdkVersion` is changed from 30 to 31.
- If the `compileSdkVersion` is a larger number like 32 it won't be lowered, this ensures the plugin has a longer shelf life.
=> [config plugin] bump to minimum Android SDK version to 31

index.d.ts, ios/NfcManager.m, src/NfcManager.js, src/NfcManagerIOS.js, src/NfcTech/Iso15693HandlerIOS.js, src/NfcTech/NfcVHandler.js, src/index.js
This PR aims to support [iso15693 sendRequest for ios](https://developer.apple.com/documentation/corenfc/nfciso15693tag/3551933-sendrequestwithflag?language=objc).
`NfcManager.iso15693HandlerIOS.sendRequest` has been added, and the function signature is:
```typescript
sendRequest: (params: {
flags: number;
commandCode: number;
data: number[];
}) => Promise<[number, number[]]>;
```
The response tuple contains 2 elements:
- the first is `response flag`, see [Apple doc](https://developer.apple.com/documentation/corenfc/nfciso15693responseflag?language=objc)
- the second is `response data`, which is a byte array.
Regarding the first `response flag` value, it's also been exported as an enum in our `index.d.ts`:
```typescript
export enum Nfc15693ResponseFlagIOS {
Error = 1 << 0, …
```
=> feat(ios): support iso15693 sendRequest

android/src/main/java/community/revteltech/nfc/NfcManager.java, index.d.ts, src/NfcTech/MifareClassicHandlerAndroid.js
There are three methods in the android mifare classic that it's should be a good idea implement it:
- increment
- decrement
- transfer.
This three methods allow you to change the value of a block easily.
The last command that i have add is authenticate with key B, because sometimes you can't write with key A and you need the key B.
I have add that methods copying and paste the writeBlock and change the name of the function and some code inside. I would recommend check it before merge into the main branch, but i can say that is working that methods perfectly, you can check it.
Also it's a good idea make some refactor code of the mifareClassicHandler, because when you call it and after you want to use a method of that class it's something like this:
`await …
=> [ENH] Add increment, decrement, transfer and authenticateKeyB

react-native-nfc-manager.podspec
React-Native: 0.68.1
react-native-nfc-manager: 3.11.0
expo: 44.0.0
XCode: 13.3.1 (13E500a)
```json
"dependencies": {
"@react-native-community/datetimepicker": "4.0.0",
"@react-native-community/masked-view": "0.1.11",
"@react-native-picker/picker": "2.4.1",
"@react-navigation/bottom-tabs": "^6.3.1",
"@react-navigation/native": "^6.0.10",
"@react-navigation/stack": "^6.2.1",
"axios": "^0.27.2",
"eas-cli": "^0.52.0",
"expo": "^44.0.0",
"expo-barcode-scanner": "~11.2.0",
"expo-camera": "~12.1.2",
"expo-image-manipulator": "~10.2.0",
"expo-location": "~14.0.1",
"expo-modules-autolinking": "^0.5.5",
"expo-secure-store": "~11.1.0",
"expo-splash-screen": "~0.14.1",
"expo-status-bar": "~1.2.0",
"expo-updates": "~0.11.7",
"i18n-js": "^3.8.0",
"i18next": "^21.6.16",
"i18next-http-backend": "^1.2.1", …
```
=> XCode 13 build failed fix

ios/NfcManager.m
close https://github.com/revtel/react-native-nfc-manager/issues/531
Now it looks like `NFCPollingISO18092` will not cause crash.
And scanning FeliCa tags need it.
=> Add NFCPollingISO18092 for polling on iOS

react-native-nfc-manager.podspec
My app and the demo app (https://developer.apple.com/forums/thread/106057) is crashing on iPhone 6s - iOS 12.5.5 on splash screen while it's loading CoreNFC (see Crash section below).
It's because CoreNFC is available only for iPhone 7 and higher. iPhone 6 has NFC, but it doesn't have CoreNFC (https://stackoverflow.com/questions/25753473/reading-nfc-tags-with-iphone-6-ios-8 ).
The solution is a little bit simple, I just added a flag to weak linking the CoreNFC.
it's based on this answer on stack overflow: https://stackoverflow.com/a/67398931/1489446
```
dyld: Library not loaded: /System/Library/Frameworks/CoreNFC.framework/CoreNFC
Referenced from: /var/containers/Bundle/Application/FFB5206D-8144-4DD6-815B-864023274C64/MyApp.app/Ton - Dev
Reason: image not found
(lldb) 
```
It probably …
=> fix: add CoreNFC as a waek framework to avoid crashes on devices without CoreNFC

android/src/main/java/community/revteltech/nfc/NfcManager.java, index.d.ts
also, returning a boolean value to indicate whether we can find Android system NFC settings
=> fix(android): avoid native exception while jumping to system NFC settings

app.plugin.js
Adding option `includeNdefEntitlement` to expo config plugin that when explicitly set to `false`, removes NDEF entitlement. 
Workaround for error 
`Error: Asset validation failed Invalid entitlement for core nfc framework. The sdk version '16.0' and min OS version '13.0' are not compatible for the entitlement 'com.apple.developer.nfc.readersession.formats' because 'NDEF is disallowed`
Error as seen in:
- https://stackoverflow.com/questions/58131299/xcode-testflight-validate-error-itms-90778-ndef-is-disallowed 
Doing so will allow build to be submitted to test flight.
Usage in app.json:
```
"plugins": [
[
"react-native-nfc-manager",
{
"includeNdefEntitlement": false
}
],
]
```
This is my first PR on open source, any feedback would be very much appreciated :)
=> Expo config plugin - include ndef entitlement

ios/NfcManager.m
After updating to iOS 16 in 50% cases we get error in `requestTechnology` call due to error in connecting to tag.
It is easily reproducible if we move iPhone during NFC scanning.
- changed logic to restart polling instead of raising error during sensor connection
After applying this patch it works reliably and scans without any issues on iOS 16.
Logs:
```
NFCTag didDetectTags
[CoreNFC] -[NFCTagReaderSession _connectTag:error:]:730 Error Domain=NFCError Code=100 "Tag connection lost" UserInfo={NSLocalizedDescription=Tag connection lost}
NFCTag restarting polling
NFCTag didDetectTags
[CoreNFC] -[NFCTagReaderSession _connectTag:error:]:730 Error Domain=NFCError Code=100 "Tag connection lost" UserInfo={NSLocalizedDescription=Tag connection lost}
NFCTag restarting polling
FCTag didDetectTags …
```
=> Bug: restart polling on NFC tag connection error [iOS 16]

android/src/main/java/community/revteltech/nfc/NfcManager.java
`react-native-nfc-manager` [thinks that every new intent is NFC intent](https://github.com/revtel/react-native-nfc-manager/blob/main/android/src/main/java/community/revteltech/nfc/NfcManager.java#L1297)
It leads to issue as `requestTechnology` callback is being called when `tag` is `null` every time when app returns to foreground/quick action is opened.
- added early return if `tag` is `null` in Intent
=> Bug: fix intents handling when they don't contain NFC tag [Android]

package-lock.json, package.json
Update `@expo/config-plugins` dependency to `~7.2.2` to support Expo SDK 49.
Resolution for `npx expo-doctor` error that specifies version `~7.2.2` is required:
```
Expected package @expo/config-plugins@~7.2.2
Found invalid:
@expo/config-plugins@6.0.2
@expo/config-plugins@6.0.2
@expo/config-plugins@6.0.2
```
=> bump @expo/config-plugins

android/src/main/java/community/revteltech/nfc/NfcManager.java, index.d.ts, ios/NfcManager.m, src/NfcManager.js, src/NfcTech/NdefHandler.js
On android 13, we have this kind of problem : [https://stackoverflow.com/questions/75554547/nfc-getndefmessage-returns-null-after-tag-writing-on-android-13](https://stackoverflow.com/questions/75554547/nfc-getndefmessage-returns-null-after-tag-writing-on-android-13)
This fix is needed in order to be able to read nfc device like [NHS3100](https://www.nxp.com/products/rfid-nfc/nfc-hf/ntag-smartsensor/ntag-smartsensor-with-temperature-sensor-and-digital-ios:NHS3100)
=> Reconnect ndef when an ndef is written.

android/src/main/java/community/revteltech/nfc/NfcManager.java
Hello, 
I'd like to enable the workaround for issue #661 
save the tag so the `connect()` function can use it.
In reader mode, the tag is already saved in ivar, add this for the foreground dispatch mode
Thanks,
=> fix: cache the tag for later use

android/build.gradle
By setting a namespace in android/build.gradle.
Ref: https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444
=> RN 73 support for Android with AGP 8 required

android/src/main/java/community/revteltech/nfc/Util.java
Not the fix I want but this should stop the app from crashing at least, when the tag becomes out of date. A security exception is thrown when a tag is out of date, this exception was not being caught.
I am looking deeper into this issue, hopefully I find a better solution which shouldn't even raise this exception.
=> catch security exception on out of date tags

src/NfcError.js
Hello,
Not sure if this is missed by mistake 
it could be raised on iOS 14+, calling `requestTechnology` when the NFC toggle is off in the system settings
Thanks,
=> fix: missing-radio-disabled-error

index.d.ts, ios/NfcManager.m, src/NfcManager.js, src/NfcManagerIOS.js
In some cases we might get disconnected from the NFC tag. When that happens, we are not able to communicate with the NFC tag anymore, so on iOS the only valid further step is to invalidate NFC session with an error, and ask the user to try again. It also seems to be impossible to process multiple NFC tags within a single CoreNFC tag reading session (unless I'm mistaken).
This PR implements additional method called `restartTechnologyRequestIOS` which essentialy wires the `NFCTagReaderSession.restartPolling()` into the react-native-nfc-manager. This API makes it possible to process multiple tags or to retry an NFC operation against the same tag in case of any failure, without actually restarting the NFC scanning prompt.
=> Implement restartTechnologyRequestIOS

package-lock.json, package.json
Bump `@expo/config-plugins` to be compatible with `expo 50`.
`npx expo-doctor@latest`
> ✖ Check that native modules use compatible support package versions for installed Expo SDK
Detailed check results:
Expected package @expo/config-plugins@~7.8.0
Found invalid:
@expo/config-plugins@7.2.5
Advice: Upgrade dependencies that are using the invalid package versions0.
`yarn why @expo/config-plugins`
> => Found "@expo/config-plugins@7.8.4"
> info Has been hoisted to "@expo/config-plugins"
> info Reasons this module exists
>    - Hoisted from "expo#@expo#config-plugins"
>    - Hoisted from "expo-updates#@expo#config-plugins"
>    - Hoisted from "expo#@expo#cli#@expo#config-plugins"
>    - Hoisted from "expo-splash-screen#@expo#prebuild-config#@expo#config-plugins"
>    - Hoisted from …
=> bump @expo/config-plugins from ~7.2.5 to ~7.8.0

index.d.ts
I manually connected to an `NfcV` tag by using the `connect` function of the `NfcManagerAndroid` class. However, I realized that the connect function is not exposed in the `index.d.ts` file. so I added missing methods such as connect and close to the TypeScript declaration file.
=> feat: add connect and close methods to NfcManager interface

index.d.ts, src/NfcManagerIOS.js
This PR binds the native `isSessionAvailable` and `isTagSessionAvailable` methods to the JavaScript Module. These methods are only available on iOS and can be helpful to get more information about the current nfc session states.
=> feat(NfcManagerIOS): bind native session available methods

index.d.ts, ios/NfcManager+Iso15693.m, src/NfcTech/Iso15693HandlerIOS.js
This PR introduces support for the [extendedReadMultipleBlocks](https://developer.apple.com/documentation/corenfc/nfciso15693tag/3043801-extendedreadmultipleblocks) method for NFCISO15693Tag on iOS.
=> feat: add iso15693_extendedReadMultipleBlocks

package-lock.json, package.json
Hi team,
I’ve created a PR to bump @expo/config-plugins to v10.
Version 10 of @expo/config-plugins is one of the requirements for Expo v53.
Related: https://github.com/revtel/react-native-nfc-manager/issues/782
Thanks!
=> Bump @expo/config-plugins to v10

android/src/main/java/community/revteltech/nfc/NfcManager.java, src/NfcManager.js
Hello again,
In Android NFC, the constant `EXTRA_READER_PRESENCE_CHECK_DELAY` is an optional extra you can pass when enabling reader mode. It controls how frequently Android checks whether the NFC tag is still present.
The previous implementation set it to 10 seconds which is kinda an invalid input and also only allowed passing seconds while millis can make a difference.
**Defaults:**
If you don’t set it, the JS code passes a default of **250ms now**. (androids system default is around ~125ms but there are some weird nfc chips with an aggressive polling rate from broadcom inside phones, so 250ms seems to be a good start point or default in general)
**readerModeDelay** is now expecting milliseconds!
**When to change it:**
Increase delay (e.g., 500ms–1000ms):
Saves power.
Good to try for …
=> fix(Android): correct reader mode delay handling
