revtel/react-native-nfc-manager

android/src/main/java/community/revteltech/nfc/NfcManagerPackage.java

Breaking changes in React Native 0.47
facebook/react-native@ce6fb33

Remove deprecated createJSModules @Override

---

android/src/main/java/community/revteltech/nfc/Util.java

This converts the id to a string which is equal to the Serial Number of the tag.

convert the id from a byte array to a string

---

NfcManager.js
README.md
android/src/main/java/community/revteltech/nfc/NfcManager.java

Enable to check whether NFC is supported by hardware.

add isSupported for Android

---

index.d.ts

Update TS definitions and document platform-specific functions.

Update Typescript definitions for NfcManager

---

example/App.js

A little fix in the example to avoid parse a undefined object.
Thanks you a lots.
Any idea for a IOS write version release date ?

Avoid read undefined object

---

index.d.ts

complete typings for functions not typed yet(most are android-only functions) to make the example  TS compilable.

complete typings for functions not typed yet

---

android/src/main/java/community/revteltech/nfc/NfcManager.java
android/src/main/java/community/revteltech/nfc/TagTechnologyRequest.java

Basically all nfc tech supports `transceive` method, this PR exposes them to JS side.

Support more tech (NfcB/F/V/IsoDep) with transceive method

---

NfcManager.js
android/src/main/java/community/revteltech/nfc/NfcManager.java
android/src/main/java/community/revteltech/nfc/TagTechnologyRequest.java

#106 feature request for mifare ultralight

feat: mifareultralight support (#106)

---

ndef-lib/ndef-util.js

Before, characters like "à" couldn't be parsed and they were falling back to "a"

ndef-util: handle UTF-8 encoded special characters

---

index.d.ts

idk if you want this, but here's some types I did up for Ndef-lib. 
closes #123

Add types for ndef-lib

---

index.d.ts

... so that you can supply a value for one option while keeping the defaults for others.

Make each RegisterTagEventOpts optional

---

NfcManager.js
android/src/main/java/community/revteltech/nfc/NfcManager.java
android/src/main/java/community/revteltech/nfc/TagTechnologyRequest.java

Add support of transcieve in reader mode.
I needed it for sending multiple apdu in one reading session.

Transceive in reader mode

---

android/src/main/java/community/revteltech/nfc/NfcManager.java

Get ndef from Ndef.get instead of casting techRequest in order to be able to read ndef from any tech.

Get ndef from Ndef.get

---

NfcManager.js
android/src/main/java/community/revteltech/nfc/NfcManager.java
android/src/main/java/community/revteltech/nfc/TagTechnologyRequest.java

Hello, 
I needed to be able to detect different kind of tag and send a transceive command.
This pull request allow to request multiple technologies, all of them will try to connect to the tag and the first that works will return the matching technology.

Add requestTechnologies methods to read multiple kind of tags.

---

ndef-lib/ndef-text.js

Utf 8 decode

---

index.d.ts

Hey!
Here is a fix for the issue https://github.com/whitedogg13/react-native-nfc-manager/issues/232.
Regards,
Frans L

Fix typescript declaration errors

---

APIv1.md

Added infos from closed issue #208 to readme.

added more details to getLaunchTag()

---

NfcManager.js
README.md
index.d.ts
ios/NfcManager.m

Currently, it is not compatible with Felica on iOS, so we added command transmission with Felica

Added sendFelicaCommandIOS

---

index.d.ts

@whitedogg13 Thanks for making such a useful package :)
I've added typed definitions for the `record` function if people decide to create their own custom `NdefRecord`s (which is my case)

Added types definitions for record function

---

README.md

Added a paragraph that explains the code to insert inside Info.plist for supporting Nftech.FelicaIOS

Update README.md explaining FelicaIOS requirements

---

ios/NfcManager.m

This pull request aims to solve the issue raised in [724](https://github.com/revtel/react-native-nfc-manager/issues/724).

fix: cancelTechnologyRequest leaks

---

package-lock.json
package.json

https://github.com/revtel/react-native-nfc-manager/issues/757

expo 51 & 52 support and non-expo support

---

README.md

The link in the readme returns a 404, this is the new link

Fix 404 link

---

android/src/main/java/community/revteltech/nfc/NfcManager.java
index.d.ts
specs/NativeNfcManager.ts
src/NfcManager.js
src/NfcManagerAndroid.js

Hey again,
this PR adds getTimeout also to newarch. (codegen spec added in separate commit)

feat(Android): add getTimeout new arch
